### PR TITLE
OAuth2 implementation for JHub 3.0

### PR DESCRIPTION
**Pull request by joernahlers**
The method used so far is no longer compatible with the current Jupyterhub version, so a few changes were necessary

### CODE REVIEW

**Comment by moorepants** [comment]
Will this still work with past JupyterHub versions with these changes?

**Comment by TimStewartJ** [comment]
Thanks, this looks really promising.

Is there a specific level of backward compatibility we're looking for @moorepants?

**Comment by moorepants** [comment]
> Is there a specific level of backward compatibility we're looking for @moorepants?

As much as developer resources permit and as much as desired by ngshare users.

**Comment by rubdos** [comment]
> > Is there a specific level of backward compatibility we're looking for @moorepants?
> 
> As much as developer resources permit and as much as desired by ngshare users.

Specifically, I think we really need to provide robust upgrade paths. From a first look, this does not seem to really mess something up.

**Comment by joernahlers** [comment]
Hello and sorry that I had not reported earlier, but there was other business. I think that the changes should be compatible down to Jupyterhub version 1.1, if I read the changelog of Jupyterhub correctly and have not missed anything. I haven't done a test yet, because I was glad that the change first of all lead to the fact that my Jupyterhub works again. 

The changes that were made are based on the implementation of the oauth authorization of the ngshare service in the jupyterhub. This is also only necessary for the administration side.

**Comment by TimStewartJ** [comment]
I'd say this is good to be merged. I've done a lot of testing and there seems to be no adverse effects. I can confirm compatibility all the way back to at least JupyterHub 1.3.0 and the upgrade process is seamless.

Some immediate next steps are to make unit tests compatible, which I have a fix in mind for already, and to update documentation accordingly.

Barring any pushback, I'll merge by EOD or tomorrow.

**Pull request merged**
